# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablewidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 361, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(450, 40, 301, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_tarih = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_tarih.setObjectName("line_tarih")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_tarih)
        self.line_isim = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_isim.setObjectName("line_isim")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_isim)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_tip = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_tip.setObjectName("line_tip")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_tip)
        self.line_ip = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_ip.setObjectName("line_ip")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_ip)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.line_url = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_url.setObjectName("line_url")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_url)
        self.save_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.save_button)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Tarih"))
        self.label_2.setText(_translate("MainWindow", "Tip"))
        self.label_5.setText(_translate("MainWindow", "Url"))
        self.save_button.setText(_translate("MainWindow", "Kaydet"))
        self.label.setText(_translate("MainWindow", "İsim"))
        self.label_4.setText(_translate("MainWindow", "Ip"))

